language: ruby

rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - ruby-head

matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head

branches:
  only:
    - "master"
    - "ppc64le"

cache: bundler

sudo: false

git:
  depth: 10
